### ISSUE TITLE
put all crypto in web workers (browser) or child process forks (node)

### ISSUE THREAD

**Issue by ryanxcharles** [dattnetwork/datt-node#11]
Crypto is slow and will block networking and the UI. We need to create an interface for running crypto in a web worker (browser) or child process fork (node). fullnode has an example interface that does exactly this. We need to do something similar.

One way to do this is to create a "Work" interface like fullnode that allows using any object's methods in a worker. Another option, which is perhaps simpler, but less general, is to just create an asynchronous "crypto" interface that handles basic crypto operations in its own managed workers.

**Comment by willy-b** [comment]
(reassigned because Ryan has done all the work on this item :-) )

**Comment by ryanxcharles** [comment]
Closed by https://github.com/dattnetwork/datt-node/pull/15
