### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by halseth** [dattnetwork/datt-node#16]
I get an error when running `npm run test` on latest master:

```
datt-node/gulpfile.js:89
    throw err
          ^
Error: karma exited with code 1
    at done (/datt-node/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/datt-node/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

Here is npm log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@2.13.4
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'pretest', 'test', 'posttest' ]
6 info pretest datt-node@0.0.1
7 info test datt-node@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info datt-node@0.0.1 Failed to exec test script
10 verbose stack Error: datt-node@0.0.1 test: `npm run test-node && npm run test-browser`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid datt-node@0.0.1
12 verbose cwd /datt/datt-node
13 error Darwin 14.5.0
14 error argv "node" "/usr/local/bin/npm" "run" "test"
15 error node v0.12.7
16 error npm  v2.13.4
17 error code ELIFECYCLE
18 error datt-node@0.0.1 test: `npm run test-node && npm run test-browser`
18 error Exit status 1
19 error Failed at the datt-node@0.0.1 test script 'npm run test-node && npm run test-browser'.
19 error This is most likely a problem with the datt-node package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run test-node && npm run test-browser
19 error You can get their info via:
19 error     npm owner ls datt-node
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by ryanxcharles** [comment]
Seems to work for me. Some thoughts:

- I'm running node 0.12.7. What version are you on?
- Have you tried removing node_modules and running "npm install" again?
- Do you have Chrome installed? (Since that is run by karma)
- Try running "npm run test-node" and "npm run test-browser" separately and see if they work. Also try "gulp test-node" and "gulp test-karma".

**Comment by halseth** [comment]
* Using 0.12.7
* Tried, didn't fix the issue
* "npm run test-node" passes, "npm run test-browser" throws the above error. Similar for the two gulp cases.

Can you try cloning into the a new directory and run tests again, to make sure all necessary files are included?

**Comment by ryanxcharles** [comment]
Yes I will try that.

**Comment by ryanxcharles** [comment]
No luck. I cloned a new repo, did "npm install", and the karma tests worked. I also suspected there may be a hidden "globally installed" dependency, so I tried using an older version of node (0.12.6) for which I don't have anything installed globally. The tests still passed just fine without installing anything globally.

Your problem has something to do with karma, so maybe it's actually your version of Chrome? You could try switching "chrome" to "firefox" in both the .karma.conf file and in package.json (you will need to install the karma firefox launcher - and be sure to have firefox installed). What happens then?

**Comment by halseth** [comment]
Tried with Firefox, exact same error.

I get this warning btw, a missing file?

```
26 08 2015 20:41:31.504:WARN [watcher]: Pattern "/Users/johan/Dropbox/Drive/Code/bitcoin/datt/datt-node/public/datt-node.js" does not match any file.
```

**Comment by willy-b** [comment]
Did you run "gulp" (no args) first?

**Comment by halseth** [comment]
That got rid of the warning, but  still same error.

**Comment by willy-b** [comment]
Frankly I had a lot of issues as well and reinstalled nodejs / reinstalled
all global modules, and then it worked. So there's something a bit finicky
in this PR. I think it's the workerpool module.

Can you post the failing tests?

**Comment by ryanxcharles** [comment]
I'm trying to debug this, but "npm install" takes for freaking ever for some reason, making it really difficult to try changing things. It's possibly either the workerpool module as Willy suggests, or perhaps some other dependency involved in building for the browser, or perhaps some fluke thing with OSX. Not sure. Will keep investigating slowly while I wait for "npm install" to finish.

**Comment by ryanxcharles** [comment]
I was able to test in node 0.12.5 and things worked. If karma keeps giving you trouble, there is another way to run the tests in a browser with the tests.html file. Run:

```
npm install
npm install -g gulp
gulp
./bin/testapp.js
```
...from inside the datt-node repo, then open up http://localhost:3000/tests.html in your browser, and the mocha tests will run that way.

**Comment by halseth** [comment]
Ok, that works! Thanks.
