### ISSUE TITLE
Filtered ContentStore / Peer Events are re-emitted by Datt

### ISSUE THREAD

**Issue by willy-b** [dattnetwork/datt-node#34]
To reduce the interface coupling (and technical debt) between the ContentStore, Peer, and Datt modules, let's propagate events from ContentStore/Peer -> Datt. UI/Datt processing would be driven by events on Datt itself. This is as opposed to subscribing directly to the other modules.

**Comment by halseth** [comment]
Yes, this is exactly what I was hoping for. I will start looking at event emitting (kinda new to me as well)
