### ISSUE TITLE
database abstraction over leveldb and IndexedDB

### ISSUE THREAD

**Issue by ryanxcharles** [dattnetwork/datt-node#8]
This has been partially finished in the contentStore-*.js files.

**Comment by willy-b** [comment]
See github.com/willy-b/datt-node , using PouchDB now, only one contentStore.JS .

**Comment by willy-b** [comment]
Will be merging today; need to move to the new web workers based crypto for content and contentStore (40 tests worth of operations added to mostly content.js )

**Comment by ryanxcharles** [comment]
Resolved in https://github.com/dattnetwork/datt-node/pull/17
